Backpropogation

In [1]:
import torch

In [2]:
x = torch.tensor(4.0, requires_grad=True) #requires_grad should be set to True to implement backpropogation

In [3]:
x

tensor(4., requires_grad=True)

In [4]:
y=x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [5]:
#Implement backpropogation  for y=x**2
y.backward()

In [6]:
print(x.grad)

tensor(8.)


Backpropogation for list of values

In [7]:
lst = [[2., 3., 1.], [4., 5., 3.], [7., 6., 4.]]
torch_input = torch.tensor(lst, requires_grad=True)

In [8]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [10]:
# y = x**3 + x**2
# derivative of y with respect to y will be = 3x**2 + 2x
y = torch_input**3 + torch_input**2
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [12]:
z = y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [13]:
z.backward()

In [14]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])