<a href="https://colab.research.google.com/github/bala1802/PyTorch/blob/master/Pytorch_NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import numpy as np
import torchvision # provide access to datasets, models, transforms, utils, etc
import torchvision.transforms as transforms

In [2]:
import torch.nn.functional as F
class Network(nn.Module):
    def __init__(self):
        super().__init__() #Initializes the Network parameters which is overriden from the Super Class - Network Module (nn.Module)
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5) #Image 28 X 28
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)

        self.fc1 = nn.Linear(in_features=12 * 4 * 4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)

    def forward(self, t):
        # (1) input layer
        t = t

        # (2) hidden conv layer
        t = self.conv1(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=2)

        # (3) hidden conv layer
        t = self.conv2(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=2)

        # (4) hidden linear layer
        t = t.reshape(-1, 12 * 4 * 4)
        t = self.fc1(t)
        t = F.relu(t)

        # (5) hidden linear layer
        t = self.fc2(t)
        t = F.relu(t)

        # (6) output layer
        t = self.out(t)
        #t = F.softmax(t, dim=1)

        return t

In [3]:
network = Network()
print(network)

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)


Acceessing the Network Layers

First Convulation layer

In [4]:
network.conv1

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

Second Convulation layer

In [5]:
network.conv2

Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))

Fully Connected Layer-1

In [6]:
network.fc1

Linear(in_features=192, out_features=120, bias=True)

In [7]:
network.out

Linear(in_features=60, out_features=10, bias=True)

Accesing the Layer weight

Weights of Convolution Layer-1

In [8]:
network.conv1.weight

Parameter containing:
tensor([[[[-0.1094,  0.1232, -0.0535,  0.0827, -0.0717],
          [-0.1127, -0.0468, -0.1957, -0.0331,  0.1412],
          [-0.0131,  0.0555, -0.0399,  0.1631,  0.0085],
          [ 0.0257, -0.1747,  0.0074,  0.1522, -0.0728],
          [ 0.1848,  0.0927, -0.0161, -0.0502, -0.0481]]],


        [[[-0.1871,  0.1705,  0.1464,  0.1093, -0.0016],
          [-0.1782,  0.1948, -0.0679, -0.1947,  0.1316],
          [ 0.1618,  0.1469, -0.1262, -0.1007, -0.1110],
          [-0.1620, -0.0281, -0.0713,  0.1823,  0.1423],
          [-0.0088,  0.0250,  0.1446, -0.1029, -0.1619]]],


        [[[-0.1622,  0.1063,  0.1462,  0.1487,  0.0265],
          [ 0.1282, -0.0560,  0.1745,  0.1704, -0.1549],
          [ 0.0880, -0.1569,  0.0145, -0.0363,  0.0614],
          [-0.0021,  0.0542,  0.1979, -0.0012,  0.0017],
          [ 0.0796,  0.0783,  0.0811,  0.1213,  0.0653]]],


        [[[-0.1901,  0.1755,  0.0056,  0.1397,  0.1151],
          [ 0.1727, -0.0590,  0.0769, -0.1451, -0.1581

In [9]:
len(network.conv1.weight)

6

Weights of Convolution Layer-2

In [10]:
network.conv2.weight

Parameter containing:
tensor([[[[ 4.6069e-03,  9.9415e-03,  1.9458e-02, -7.3834e-02,  8.4272e-03],
          [ 3.9906e-02, -3.5663e-02, -7.5563e-02,  4.0415e-02,  2.2247e-02],
          [-6.8970e-02, -1.4140e-02, -5.2655e-02, -2.9415e-02, -5.7022e-02],
          [-7.2678e-02, -3.8304e-03, -4.3701e-02,  7.2914e-02, -1.2694e-02],
          [-8.0411e-02, -2.0784e-02,  1.2230e-03,  7.0517e-02, -3.0353e-02]],

         [[-4.4138e-02,  4.1964e-02,  2.2861e-02,  2.8304e-02,  9.6109e-03],
          [-5.6493e-03,  7.2118e-02,  1.4339e-02, -2.8286e-02,  5.3977e-03],
          [-5.6439e-02, -3.2194e-02,  2.5950e-03, -2.0989e-02, -1.6811e-02],
          [-4.5734e-02, -5.7532e-02, -6.6377e-02,  3.7476e-02, -5.6129e-02],
          [ 6.6251e-02,  3.0208e-02, -4.6706e-02, -5.0397e-02, -3.6941e-02]],

         [[-6.4844e-02, -7.8767e-02, -1.9038e-03,  5.9718e-02, -4.5849e-03],
          [-7.5808e-02, -4.7156e-03, -1.5272e-03,  1.5190e-02,  6.5359e-02],
          [-7.6362e-02, -7.5870e-02,  2.1670e-02, 

In [11]:
len(network.conv2.weight)

12

Weights Of Full Connected Layer-1

In [12]:
network.fc1.weight

Parameter containing:
tensor([[-0.0343,  0.0371,  0.0179,  ..., -0.0270, -0.0327,  0.0570],
        [ 0.0461,  0.0412,  0.0693,  ..., -0.0472, -0.0531,  0.0311],
        [ 0.0256, -0.0376, -0.0113,  ..., -0.0147,  0.0173,  0.0500],
        ...,
        [-0.0594,  0.0419,  0.0392,  ..., -0.0159, -0.0125,  0.0715],
        [ 0.0110, -0.0180,  0.0216,  ..., -0.0409,  0.0428,  0.0620],
        [ 0.0459, -0.0592,  0.0458,  ..., -0.0456,  0.0122, -0.0141]],
       requires_grad=True)

In [13]:
len(network.fc1.weight)

120

In [14]:
network.fc1.weight.shape

torch.Size([120, 192])

In [15]:
network.fc2.weight

Parameter containing:
tensor([[ 0.0370,  0.0068, -0.0651,  ...,  0.0400, -0.0538, -0.0179],
        [ 0.0869, -0.0133,  0.0080,  ...,  0.0239, -0.0573,  0.0779],
        [ 0.0528,  0.0494, -0.0519,  ...,  0.0623,  0.0604,  0.0613],
        ...,
        [-0.0009, -0.0115,  0.0794,  ..., -0.0724,  0.0082,  0.0058],
        [-0.0883, -0.0616, -0.0479,  ..., -0.0777, -0.0608,  0.0873],
        [ 0.0007,  0.0668, -0.0630,  ..., -0.0570, -0.0142, -0.0321]],
       requires_grad=True)

In [16]:
len(network.fc2.weight)

60

In [17]:
network.fc2.weight.shape

torch.Size([60, 120])

Network Parameters

In [18]:
for param in network.parameters():
    print(param.shape)

torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([12, 6, 5, 5])
torch.Size([12])
torch.Size([120, 192])
torch.Size([120])
torch.Size([60, 120])
torch.Size([60])
torch.Size([10, 60])
torch.Size([10])


Network Named Parameters

In [19]:
for name, param in network.named_parameters():
    print(name, '\t\t', param.shape)

conv1.weight 		 torch.Size([6, 1, 5, 5])
conv1.bias 		 torch.Size([6])
conv2.weight 		 torch.Size([12, 6, 5, 5])
conv2.bias 		 torch.Size([12])
fc1.weight 		 torch.Size([120, 192])
fc1.bias 		 torch.Size([120])
fc2.weight 		 torch.Size([60, 120])
fc2.bias 		 torch.Size([60])
out.weight 		 torch.Size([10, 60])
out.bias 		 torch.Size([10])


Download Fashion MNSIT Dataset

In [23]:
train_set = torchvision.datasets.FashionMNIST(
    root='./data'
    ,train=True
    ,download=True
    ,transform=transforms.Compose([
        transforms.ToTensor()
    ])
)

Extracting ./data/FashionMNIST/raw/train-images-idx3-ubyte.gz to ./data/FashionMNIST/raw


Extracting ./data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to ./data/FashionMNIST/raw


Extracting ./data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to ./data/FashionMNIST/raw


Extracting ./data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/FashionMNIST/raw
Processing...




/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:480: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)



Done!


We can turn the dynamic graphing/gradients feature OFF, since we aren't going to be training it for sometime. It also saves memory

In [24]:
torch.set_grad_enabled(False)

In [25]:
sample = next(iter(train_set)) 
image, label = sample
image.shape

torch.Size([1, 28, 28])

The Shape of the image - [1, 28, 28] won't be supported while training the Images. So we'll be unsqueezing it to [1, 1, 28, 28] 

- The first '1' represents the size of the batch
- The second '1' represents the number of input channels
- 28 X 28 represents the Height X Width

In [26]:
image.unsqueeze(0).shape

torch.Size([1, 1, 28, 28])

In [27]:
network = Network()
pred = network(image.unsqueeze(0)) # image shape needs to be (batch_size × in_channels × H × W)

In [28]:
pred

tensor([[-0.0608,  0.0192, -0.1254,  0.0119,  0.0441, -0.1119,  0.0673, -0.0567,
          0.0969, -0.1175]])

The Shape should be 10, coz the number of classes in the training set is 10

In [29]:
pred.shape

torch.Size([1, 10])

In [30]:
label # The Label should be predicted

9

In [31]:
pred.argmax(dim=1) # Find the maximum value in the tensor used 'argmax'

tensor([8])

In [32]:
F.softmax(pred, dim=1)

tensor([[0.0960, 0.1040, 0.0900, 0.1033, 0.1066, 0.0912, 0.1092, 0.0964, 0.1124,
         0.0907]])

Working with multiple images - Dataloader is used

In [33]:
data_loader = torch.utils.data.DataLoader(
    train_set, 
    batch_size=10
)

batch = next(iter(data_loader))
len(batch) # Length of the batches is 2

2

In [34]:
batch[1] # The labels total 10
# batch[0] # The Images total 10

tensor([9, 0, 0, 3, 0, 2, 7, 2, 5, 5])

Notice that the label is 9

In [35]:
images, labels = batch
images.shape

torch.Size([10, 1, 28, 28])

From the above, The Shape of the Images is [10, 1, 28, 28] => 10 is the number of batches, 1 is the number of channels, 28X28 is HXW

Here the unsqueeze operation is not needed, coz the batch size is already configured as 10

In [36]:
preds = network(images)
preds.shape

torch.Size([10, 10])

In [37]:
preds

tensor([[-0.0608,  0.0192, -0.1254,  0.0119,  0.0441, -0.1119,  0.0673, -0.0567,
          0.0969, -0.1175],
        [-0.0622,  0.0148, -0.1322,  0.0112,  0.0394, -0.1113,  0.0683, -0.0553,
          0.0995, -0.1148],
        [-0.0580,  0.0204, -0.1213,  0.0047,  0.0438, -0.1081,  0.0641, -0.0527,
          0.0965, -0.1084],
        [-0.0600,  0.0213, -0.1223,  0.0069,  0.0448, -0.1071,  0.0669, -0.0537,
          0.0976, -0.1104],
        [-0.0580,  0.0180, -0.1239,  0.0080,  0.0411, -0.1093,  0.0685, -0.0579,
          0.0995, -0.1153],
        [-0.0602,  0.0233, -0.1251,  0.0094,  0.0413, -0.1102,  0.0689, -0.0579,
          0.0981, -0.1108],
        [-0.0569,  0.0186, -0.1222,  0.0113,  0.0481, -0.1074,  0.0658, -0.0616,
          0.0989, -0.1091],
        [-0.0616,  0.0186, -0.1262,  0.0096,  0.0438, -0.1096,  0.0663, -0.0550,
          0.0952, -0.1092],
        [-0.0625,  0.0171, -0.1156,  0.0019,  0.0462, -0.1108,  0.0696, -0.0546,
          0.0952, -0.1098],
        [-0.0589,  

In [38]:
preds.argmax(dim=1)

tensor([8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [39]:
preds.argmax(dim=1).eq(labels)

tensor([False, False, False, False, False, False, False, False, False, False])

Batch-1 Actual labels

tensor([9, 0, 0, 3, 0, 2, 7, 2, 5, 5])

In [40]:
preds.argmax(dim=1).eq(labels).sum()

tensor(0)

In [41]:
def get_num_correct(preds, labels):
  return preds.argmax(dim=1).eq(labels).sum().item()

In [42]:
get_num_correct(preds, labels)

0

Training the Neural Network:

During the entire training process, we do as many epochs as necessary to reach our desired level of accuracy. With this, we have the following steps:

1. Get batch from the training set.
2. Pass batch to network.
3. Calculate the loss (difference between the predicted values and the true values).
4. Calculate the gradient of the loss function w.r.t the network's weights.
5. Update the weights using the gradients to reduce the loss.
6. Repeat Step 1-5 for 1 epoch

Repeat steps 1-6 for as many epochs required to reach the minimum loss.

In [46]:
import torch.optim as optim
torch.set_grad_enabled(True) # Enabling the Gradient, to calculate the weights and losses during the Training

In [47]:
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item()

0.4108503460884094

In [48]:
print(network.conv1.weight.grad) # currently there are no gradients

tensor([[[[-4.5554e-02, -8.1278e-03,  2.0720e-02,  5.0532e-05, -1.9347e-02],
          [-1.7887e-02,  1.2773e-03,  1.8819e-02,  1.6537e-03, -9.4407e-04],
          [-2.6078e-02, -1.5808e-06, -9.8512e-04,  9.7621e-03,  7.5890e-03],
          [-2.9526e-02,  5.8620e-03,  3.8031e-02,  1.4704e-02,  5.0562e-02],
          [-4.4065e-02, -1.7557e-02,  6.4156e-02,  3.5995e-02,  4.7536e-02]]],


        [[[-7.1064e-03, -8.6988e-03, -4.2182e-03,  3.5202e-03,  1.6302e-02],
          [ 2.9871e-03, -1.6721e-03, -2.5711e-03,  1.4360e-03,  6.5920e-03],
          [ 3.3430e-03, -2.3192e-03, -7.3791e-03,  1.7482e-03,  8.1677e-03],
          [ 4.0630e-03, -2.2341e-03, -6.0833e-03,  7.5855e-03,  8.9707e-03],
          [ 2.3287e-03, -3.3164e-04,  1.0487e-03,  1.0518e-02,  1.6617e-02]]],


        [[[ 2.1942e-02,  7.2879e-03, -3.1980e-03,  2.1540e-02,  4.2614e-02],
          [ 1.6619e-02,  3.8741e-03,  2.7578e-02,  5.9055e-02,  4.8348e-02],
          [ 2.1107e-02,  4.8402e-02,  4.9228e-02,  5.9019e-02,  4.73

In [ ]:
loss.backward() #Backward propogation

In [49]:
print(network.conv1.weight.grad) #Now we can see the gradients

tensor([[[[-4.5554e-02, -8.1278e-03,  2.0720e-02,  5.0532e-05, -1.9347e-02],
          [-1.7887e-02,  1.2773e-03,  1.8819e-02,  1.6537e-03, -9.4407e-04],
          [-2.6078e-02, -1.5808e-06, -9.8512e-04,  9.7621e-03,  7.5890e-03],
          [-2.9526e-02,  5.8620e-03,  3.8031e-02,  1.4704e-02,  5.0562e-02],
          [-4.4065e-02, -1.7557e-02,  6.4156e-02,  3.5995e-02,  4.7536e-02]]],


        [[[-7.1064e-03, -8.6988e-03, -4.2182e-03,  3.5202e-03,  1.6302e-02],
          [ 2.9871e-03, -1.6721e-03, -2.5711e-03,  1.4360e-03,  6.5920e-03],
          [ 3.3430e-03, -2.3192e-03, -7.3791e-03,  1.7482e-03,  8.1677e-03],
          [ 4.0630e-03, -2.2341e-03, -6.0833e-03,  7.5855e-03,  8.9707e-03],
          [ 2.3287e-03, -3.3164e-04,  1.0487e-03,  1.0518e-02,  1.6617e-02]]],


        [[[ 2.1942e-02,  7.2879e-03, -3.1980e-03,  2.1540e-02,  4.2614e-02],
          [ 1.6619e-02,  3.8741e-03,  2.7578e-02,  5.9055e-02,  4.8348e-02],
          [ 2.1107e-02,  4.8402e-02,  4.9228e-02,  5.9019e-02,  4.73

In [51]:
network.conv1.weight.grad.shape #6 kernels of size 5 x 5

torch.Size([6, 1, 5, 5])

In [52]:
optimizer = optim.SGD(network.parameters(), lr=0.01)
loss.item()

0.4108503460884094

In [53]:
get_num_correct(preds, labels)

85

In [55]:
optimizer.step() #Weights get updated based on the Gradient

In [56]:
preds = network(images)
loss = F.cross_entropy(preds, labels)
loss.item()

0.39171966910362244

In [57]:
get_num_correct(preds, labels)

85

In [58]:
preds = network(images)
loss = F.cross_entropy(preds, labels)
print(loss.item(), get_num_correct(preds, labels))
optimizer.step()

0.39171966910362244 85


In [59]:
preds = network(images)
loss = F.cross_entropy(preds, labels)
print(loss.item(), get_num_correct(preds, labels))
optimizer.step()

0.38243651390075684 85


In [60]:
preds = network(images)
loss = F.cross_entropy(preds, labels)
print(loss.item(), get_num_correct(preds, labels))
optimizer.step()

0.37305358052253723 85


For more than One Epoch

- Number of Batches 600
- 1 Batch Contains 100 Images
- Total = 600 * 100 = 60000 Images

all together the training is done for 10 epochs

In [68]:
train_loader = torch.utils.data.DataLoader(train_set, batch_size=100)
optimizer = optim.Adam(network.parameters(), lr=0.01)

for epoch in range(10):
    total_loss = 0
    total_correct = 0

    for batch in train_loader: # Get Batch #Getting a batch of 100 images
        images, labels = batch # The total number of Images is 100, Labels is 100
        # Shape of the Image is (100, 1, 28, 28) 100 is total images in the batch, 1 is the channel size, 28 X 28 is the H X W of an image
        preds = network(images) # Pass Batch total of 100 images
        # Shape of the Preds is ([100, 10]) 100 rows of 10 classes (labels)
        loss = F.cross_entropy(preds, labels) # Calculate Loss. BY passing the 'Prdictions - 100' and Actual 'Labels - 100'

        optimizer.zero_grad() # Asking the network to clear the previously stored gradients
        loss.backward() # Calculate Gradients
        optimizer.step() # Update Weights

        total_loss += loss.item()
        total_correct += get_num_correct(preds, labels)

        batchCounter += 1

    print(
        "epoch", epoch, 
        "total_correct:", total_correct, 
        "loss:", total_loss
    )

epoch 0 total_correct: 53286 loss: 194.40297675132751
epoch 1 total_correct: 53767 loss: 173.87910921871662
epoch 2 total_correct: 53976 loss: 163.18272931873798
epoch 3 total_correct: 53480 loss: 182.08285769075155
epoch 4 total_correct: 53920 loss: 165.84323486685753
epoch 5 total_correct: 53953 loss: 165.24212615936995
epoch 6 total_correct: 53737 loss: 174.59074488282204
epoch 7 total_correct: 54095 loss: 159.9184528440237
epoch 8 total_correct: 53629 loss: 176.3818168118596
epoch 9 total_correct: 54072 loss: 160.60015588253736
